# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(321, 581)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(321, 581))
        MainWindow.setMaximumSize(QtCore.QSize(321, 581))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/qualifications.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#centralwidget{\n"
"    background-color: rgb(170, 85, 127);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color: rgb(235,235,235,30);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover, #show_calc_note_avr:hover, #show_calc_final_note:hover {\n"
"padding:nope;\n"
"border: 1px solid rgb(190,190,190);\n"
"background-color: rgb(235,235,235);\n"
"}\n"
"\n"
"\n"
"\n"
"QLabel, QPushButton, QLineEdit{\n"
"background-color: rgb(230,230,230);\n"
"border: 1px solid rgb(190,190,190);\n"
"border-radius: 15px;\n"
"color: rgb(50,50,50)\n"
"}\n"
"\n"
"QObject{\n"
"\n"
"font: 63 10pt \"Bahnschrift SemiBold\";\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(230,230,230);\n"
"border: 1px solid rgb(190,190,190);\n"
"border-radius: 15px;\n"
"padding-left: 8px;\n"
"\n"
"}\n"
"\n"
"QGroupBox{\n"
"font: 63 12pt \"Bahnschrift SemiBold\";\n"
"color: rgb(50,50,50); \n"
"background-color: rgb(220,220,220,200);\n"
"border-bottom-right-radius: 30px;\n"
"border-bottom-left-radius: 30px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.groupbox_note_avr = QtWidgets.QGroupBox(self.centralwidget)
        self.groupbox_note_avr.setGeometry(QtCore.QRect(40, 280, 241, 261))
        self.groupbox_note_avr.setStyleSheet("Groupbox{\n"
"font: 12pt \"Segoe Fluent Icons\";}")
        self.groupbox_note_avr.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupbox_note_avr.setObjectName("groupbox_note_avr")
        self.show_note_avr_percent_vize1 = QtWidgets.QLabel(self.groupbox_note_avr)
        self.show_note_avr_percent_vize1.setGeometry(QtCore.QRect(180, 40, 41, 41))
        self.show_note_avr_percent_vize1.setStyleSheet("padding:nope;")
        self.show_note_avr_percent_vize1.setAlignment(QtCore.Qt.AlignCenter)
        self.show_note_avr_percent_vize1.setObjectName("show_note_avr_percent_vize1")
        self.lineedit_note_avr_vize1 = QtWidgets.QLineEdit(self.groupbox_note_avr)
        self.lineedit_note_avr_vize1.setGeometry(QtCore.QRect(20, 40, 71, 41))
        self.lineedit_note_avr_vize1.setStyleSheet("")
        self.lineedit_note_avr_vize1.setText("")
        self.lineedit_note_avr_vize1.setMaxLength(3)
        self.lineedit_note_avr_vize1.setObjectName("lineedit_note_avr_vize1")
        self.dial_note_avr_vize1 = QtWidgets.QDial(self.groupbox_note_avr)
        self.dial_note_avr_vize1.setGeometry(QtCore.QRect(110, 40, 41, 41))
        self.dial_note_avr_vize1.setMaximum(20)
        self.dial_note_avr_vize1.setSingleStep(2)
        self.dial_note_avr_vize1.setProperty("value", 6)
        self.dial_note_avr_vize1.setNotchesVisible(True)
        self.dial_note_avr_vize1.setObjectName("dial_note_avr_vize1")
        self.text_note_avr_vize1 = QtWidgets.QLabel(self.groupbox_note_avr)
        self.text_note_avr_vize1.setGeometry(QtCore.QRect(155, 40, 31, 41))
        self.text_note_avr_vize1.setStyleSheet("border: nope;\n"
"background-color:transparent;")
        self.text_note_avr_vize1.setAlignment(QtCore.Qt.AlignCenter)
        self.text_note_avr_vize1.setObjectName("text_note_avr_vize1")
        self.show_note_avr_percent_vize2 = QtWidgets.QLabel(self.groupbox_note_avr)
        self.show_note_avr_percent_vize2.setGeometry(QtCore.QRect(180, 90, 41, 41))
        self.show_note_avr_percent_vize2.setStyleSheet("padding:nope;")
        self.show_note_avr_percent_vize2.setAlignment(QtCore.Qt.AlignCenter)
        self.show_note_avr_percent_vize2.setObjectName("show_note_avr_percent_vize2")
        self.lineedit_note_avr_vize2 = QtWidgets.QLineEdit(self.groupbox_note_avr)
        self.lineedit_note_avr_vize2.setGeometry(QtCore.QRect(20, 90, 71, 41))
        self.lineedit_note_avr_vize2.setMaxLength(3)
        self.lineedit_note_avr_vize2.setObjectName("lineedit_note_avr_vize2")
        self.text_note_avr_vize1_2 = QtWidgets.QLabel(self.groupbox_note_avr)
        self.text_note_avr_vize1_2.setGeometry(QtCore.QRect(155, 90, 31, 41))
        self.text_note_avr_vize1_2.setStyleSheet("border: nope;\n"
"background-color:transparent;")
        self.text_note_avr_vize1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.text_note_avr_vize1_2.setObjectName("text_note_avr_vize1_2")
        self.dial_note_avr_vize2 = QtWidgets.QDial(self.groupbox_note_avr)
        self.dial_note_avr_vize2.setGeometry(QtCore.QRect(110, 90, 41, 41))
        self.dial_note_avr_vize2.setMaximum(20)
        self.dial_note_avr_vize2.setSingleStep(2)
        self.dial_note_avr_vize2.setProperty("value", 6)
        self.dial_note_avr_vize2.setNotchesVisible(True)
        self.dial_note_avr_vize2.setObjectName("dial_note_avr_vize2")
        self.show_note_avr_percent_final = QtWidgets.QLabel(self.groupbox_note_avr)
        self.show_note_avr_percent_final.setGeometry(QtCore.QRect(180, 140, 41, 41))
        self.show_note_avr_percent_final.setStyleSheet("padding:nope;")
        self.show_note_avr_percent_final.setAlignment(QtCore.Qt.AlignCenter)
        self.show_note_avr_percent_final.setObjectName("show_note_avr_percent_final")
        self.lineedit_note_avr_final = QtWidgets.QLineEdit(self.groupbox_note_avr)
        self.lineedit_note_avr_final.setGeometry(QtCore.QRect(20, 140, 71, 41))
        self.lineedit_note_avr_final.setMaxLength(3)
        self.lineedit_note_avr_final.setObjectName("lineedit_note_avr_final")
        self.text_note_avr_vize1_3 = QtWidgets.QLabel(self.groupbox_note_avr)
        self.text_note_avr_vize1_3.setGeometry(QtCore.QRect(155, 140, 31, 41))
        self.text_note_avr_vize1_3.setStyleSheet("border: nope;\n"
"background-color:transparent;")
        self.text_note_avr_vize1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.text_note_avr_vize1_3.setObjectName("text_note_avr_vize1_3")
        self.button_note_avr = QtWidgets.QPushButton(self.groupbox_note_avr)
        self.button_note_avr.setGeometry(QtCore.QRect(120, 200, 101, 41))
        self.button_note_avr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_note_avr.setObjectName("button_note_avr")
        self.show_calc_note_avr = QtWidgets.QLabel(self.groupbox_note_avr)
        self.show_calc_note_avr.setGeometry(QtCore.QRect(20, 200, 71, 41))
        self.show_calc_note_avr.setStyleSheet("")
        self.show_calc_note_avr.setText("")
        self.show_calc_note_avr.setAlignment(QtCore.Qt.AlignCenter)
        self.show_calc_note_avr.setObjectName("show_calc_note_avr")
        self.groupbox_final_note = QtWidgets.QGroupBox(self.centralwidget)
        self.groupbox_final_note.setGeometry(QtCore.QRect(40, 40, 241, 211))
        self.groupbox_final_note.setStyleSheet("")
        self.groupbox_final_note.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupbox_final_note.setFlat(False)
        self.groupbox_final_note.setObjectName("groupbox_final_note")
        self.show_final_note_percent_vize1 = QtWidgets.QLabel(self.groupbox_final_note)
        self.show_final_note_percent_vize1.setGeometry(QtCore.QRect(180, 40, 41, 41))
        self.show_final_note_percent_vize1.setStyleSheet("padding:nope;")
        self.show_final_note_percent_vize1.setAlignment(QtCore.Qt.AlignCenter)
        self.show_final_note_percent_vize1.setObjectName("show_final_note_percent_vize1")
        self.lineedit_final_note_vize1 = QtWidgets.QLineEdit(self.groupbox_final_note)
        self.lineedit_final_note_vize1.setGeometry(QtCore.QRect(20, 40, 71, 41))
        self.lineedit_final_note_vize1.setMaxLength(3)
        self.lineedit_final_note_vize1.setObjectName("lineedit_final_note_vize1")
        self.dial_final_note_vize1 = QtWidgets.QDial(self.groupbox_final_note)
        self.dial_final_note_vize1.setGeometry(QtCore.QRect(110, 40, 41, 41))
        self.dial_final_note_vize1.setMaximum(20)
        self.dial_final_note_vize1.setSingleStep(2)
        self.dial_final_note_vize1.setPageStep(0)
        self.dial_final_note_vize1.setProperty("value", 6)
        self.dial_final_note_vize1.setOrientation(QtCore.Qt.Horizontal)
        self.dial_final_note_vize1.setInvertedAppearance(False)
        self.dial_final_note_vize1.setInvertedControls(False)
        self.dial_final_note_vize1.setWrapping(False)
        self.dial_final_note_vize1.setNotchTarget(0.0)
        self.dial_final_note_vize1.setNotchesVisible(True)
        self.dial_final_note_vize1.setObjectName("dial_final_note_vize1")
        self.text_final_note_vize1 = QtWidgets.QLabel(self.groupbox_final_note)
        self.text_final_note_vize1.setGeometry(QtCore.QRect(155, 40, 31, 41))
        self.text_final_note_vize1.setStyleSheet("border: nope;\n"
"background-color:transparent;\n"
"")
        self.text_final_note_vize1.setAlignment(QtCore.Qt.AlignCenter)
        self.text_final_note_vize1.setObjectName("text_final_note_vize1")
        self.show_final_note_percent_vize2 = QtWidgets.QLabel(self.groupbox_final_note)
        self.show_final_note_percent_vize2.setGeometry(QtCore.QRect(180, 90, 41, 41))
        self.show_final_note_percent_vize2.setStyleSheet("padding:nope;")
        self.show_final_note_percent_vize2.setAlignment(QtCore.Qt.AlignCenter)
        self.show_final_note_percent_vize2.setObjectName("show_final_note_percent_vize2")
        self.lineedit_final_note_vize2 = QtWidgets.QLineEdit(self.groupbox_final_note)
        self.lineedit_final_note_vize2.setGeometry(QtCore.QRect(20, 90, 71, 41))
        self.lineedit_final_note_vize2.setMaxLength(3)
        self.lineedit_final_note_vize2.setObjectName("lineedit_final_note_vize2")
        self.text_final_note_vize2 = QtWidgets.QLabel(self.groupbox_final_note)
        self.text_final_note_vize2.setGeometry(QtCore.QRect(155, 90, 31, 41))
        self.text_final_note_vize2.setStyleSheet("border: nope;\n"
"background-color:transparent;")
        self.text_final_note_vize2.setAlignment(QtCore.Qt.AlignCenter)
        self.text_final_note_vize2.setObjectName("text_final_note_vize2")
        self.dial_final_note_vize2 = QtWidgets.QDial(self.groupbox_final_note)
        self.dial_final_note_vize2.setGeometry(QtCore.QRect(110, 90, 41, 41))
        self.dial_final_note_vize2.setMaximum(20)
        self.dial_final_note_vize2.setSingleStep(2)
        self.dial_final_note_vize2.setProperty("value", 6)
        self.dial_final_note_vize2.setSliderPosition(6)
        self.dial_final_note_vize2.setNotchesVisible(True)
        self.dial_final_note_vize2.setObjectName("dial_final_note_vize2")
        self.button_final_note = QtWidgets.QPushButton(self.groupbox_final_note)
        self.button_final_note.setGeometry(QtCore.QRect(120, 150, 101, 41))
        self.button_final_note.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_final_note.setObjectName("button_final_note")
        self.show_calc_final_note = QtWidgets.QLabel(self.groupbox_final_note)
        self.show_calc_final_note.setGeometry(QtCore.QRect(20, 150, 71, 41))
        self.show_calc_final_note.setStyleSheet("")
        self.show_calc_final_note.setText("")
        self.show_calc_final_note.setAlignment(QtCore.Qt.AlignCenter)
        self.show_calc_final_note.setObjectName("show_calc_final_note")
        self.text_by_anil = QtWidgets.QLabel(self.centralwidget)
        self.text_by_anil.setGeometry(QtCore.QRect(170, 545, 111, 31))
        self.text_by_anil.setStyleSheet("#text_by_anil{\n"
"\n"
"background-color: transparent;\n"
"border:nope;\n"
"color: rgba(50,50,50,50) }\n"
"\n"
"#text_by_anil:hover{\n"
"\n"
"background-color: transparent;\n"
"border:nope;\n"
"color: rgba(50, 50,50, 100)\n"
"}")
        self.text_by_anil.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_by_anil.setObjectName("text_by_anil")
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(40, 550, 61, 21))
        self.button_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_clear.setStyleSheet("#button_clear{\n"
"border: none;\n"
"background: transparent;}\n"
"\n"
"#button_clear:hover{\n"
"border: none;\n"
"background: transparent;\n"
"text-decoration: underline;\n"
"}\n"
"\n"
"")
        self.button_clear.setObjectName("button_clear")
        self.warning_note_avr = QtWidgets.QLabel(self.centralwidget)
        self.warning_note_avr.setGeometry(QtCore.QRect(40, 260, 241, 16))
        self.warning_note_avr.setStyleSheet("background-color: transparent;\n"
"border: n;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"color:red;\n"
"")
        self.warning_note_avr.setText("")
        self.warning_note_avr.setObjectName("warning_note_avr")
        self.warning_final_note = QtWidgets.QLabel(self.centralwidget)
        self.warning_final_note.setGeometry(QtCore.QRect(40, 20, 241, 16))
        self.warning_final_note.setStyleSheet("background-color: transparent;\n"
"border: n;\n"
"font: 63 9pt \"Bahnschrift SemiBold\";\n"
"color:red;\n"
"")
        self.warning_final_note.setText("")
        self.warning_final_note.setObjectName("warning_final_note")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grade Calculator"))
        self.groupbox_note_avr.setTitle(_translate("MainWindow", "Not Ortalaması"))
        self.show_note_avr_percent_vize1.setText(_translate("MainWindow", "30"))
        self.lineedit_note_avr_vize1.setPlaceholderText(_translate("MainWindow", "1. Vize"))
        self.text_note_avr_vize1.setText(_translate("MainWindow", "%"))
        self.show_note_avr_percent_vize2.setText(_translate("MainWindow", "30"))
        self.lineedit_note_avr_vize2.setPlaceholderText(_translate("MainWindow", "2. Vize"))
        self.text_note_avr_vize1_2.setText(_translate("MainWindow", "%"))
        self.show_note_avr_percent_final.setText(_translate("MainWindow", "40"))
        self.lineedit_note_avr_final.setPlaceholderText(_translate("MainWindow", "Final"))
        self.text_note_avr_vize1_3.setText(_translate("MainWindow", "%"))
        self.button_note_avr.setText(_translate("MainWindow", "Hesapla!"))
        self.groupbox_final_note.setTitle(_translate("MainWindow", "Final Notu"))
        self.show_final_note_percent_vize1.setText(_translate("MainWindow", "30"))
        self.lineedit_final_note_vize1.setPlaceholderText(_translate("MainWindow", "1. Vize"))
        self.text_final_note_vize1.setText(_translate("MainWindow", "%"))
        self.show_final_note_percent_vize2.setText(_translate("MainWindow", "30"))
        self.lineedit_final_note_vize2.setPlaceholderText(_translate("MainWindow", "2. Vize"))
        self.text_final_note_vize2.setText(_translate("MainWindow", "%"))
        self.button_final_note.setText(_translate("MainWindow", "Hesapla!"))
        self.text_by_anil.setText(_translate("MainWindow", "by Anıl Ergan"))
        self.button_clear.setText(_translate("MainWindow", "Sıfırla"))
import images_rc
